### ISSUE TITLE
ctx enter instead of ctx switch

### ISSUE THREAD

**Issue by shirk3y** [grn/bash-ctx#2]
When I'm not in any context and want to enter existing one, I'm looking for command `enter`, but `switch` name fits only if I'm already in some context.

**Comment by gregnavis** [comment]
I agree that the name `enter` is more suitable than `switch`. However, I'm not sure what is the best semantics for this command when I'm already in a context. I'd love to hear your thoughts about the issue.

For instance, if I call `ctx enter project1` (or, currently, `ctx switch project1`) then should `ctx enter project2` leave `project1` and enter `project2`? Should it report an error that a context is already activated?

This is tangentially related to the issue you raised as the name should reflect the purpose of the command (`switch` can mean leave the current context and enter another one; `enter` can mean enter the given context unless some context is active).

This seems innocent on the surface but keep in mind that the `leave` script can contain potentially destructive (e.g. deactivating a project-specific service) operations. Imagine that you're working on a project, start a long-running task (e.g. the whole test suite) and then want to work on something else in the meantime. You switch the context and them boom! The test suite crashes because you stopped something essential to its execution.

The question we're facing is then: do we want to support automatic switching form a context to a different one?

If no then `enter`/`leave` are the right commands (and `enter` should fail when a context is already active).

If yes then we have a couple of choices:
1. make `enter` work only when no context is active and implement `switch` for switching (but then you can harm yourself with `ctx switch` so that doesn't seem to be a huge improvement)
2. make `enter` fail in a context unless given a flag (e.g. `ctx enter project2` fails when already in `project1`; if you want to switch run `ctx enter -f project2`)
3. make `enter` ask the user for confirmation when run in a context
4. make `enter` always fail and require the user to leave the current context explicitly

Personally, I think I like option 4 the most. The intent of `bash-ctx` is interactive use. You don't switch contexts _that_ often so typing one command to make things safe is not a huge problem. It may make usage in scripts more difficult but scripting is _not_ the primary purpose of this software.

What do you think?

**Comment by shirk3y** [comment]
My idea refers to how virtualenvwrapper works. You have only one command (workon) to enter context and to switch it. 
You mentioned that you could have long-running task that may be broken due to context switching, but this task will probably run in another shell (of course if you don't put task to the background), so its context doesn't change.

**Comment by gregnavis** [comment]
Let's choose option 4 then (`enter` fails when already in context unless you call `leave` explicitly), right?
